-- Additive migration: the unified inbound+outbound log for Messa's own
-- personal-inbox email (<local-part>@config.TEXTMESSA_EMAIL_DOMAIN -- see
-- migrations/013_personal_email.sql for address provisioning, which this
-- does NOT replace). migrations/013's inbound_personal_emails table is
-- deliberately left alone (a handful of already-tested rows, no ongoing
-- writes) rather than migrated/renamed, per this project's additive-only
-- migration philosophy -- dedup for new inbound mail now happens against
-- THIS table's own message_id UNIQUE constraint instead (see
-- db.log_inbound_personal_email).
--
-- One row per email, either direction:
--   direction            'inbound' (arrived at the user's Messa address) or
--                         'outbound' (sent from it, by Messa or the user).
--   thread_id             Computed from RFC 5322 threading headers (see
--                         db._compute_thread_id): the root message's own
--                         message_id if this message carries References/
--                         In-Reply-To pointing at one, otherwise this
--                         message's own message_id (it's starting a new
--                         thread). Every message in one conversation shares
--                         the same thread_id regardless of arrival order.
--   message_id            This message's own RFC 5322 Message-ID. Inbound:
--                         whatever the sender's mail client set. Outbound:
--                         generated by channels/resend.py itself (not
--                         trusted to Resend's API response) and set as an
--                         explicit header on the send, so we know the exact
--                         value up front rather than parsing it back out.
--                         UNIQUE -- doubles as the dedup key for redelivered
--                         inbound webhooks (ON CONFLICT DO NOTHING).
--   in_reply_to/references Kept as their own columns (not just folded into
--                         raw_json) so thread_id can be recomputed later
--                         from a plain query if the algorithm ever changes,
--                         without parsing every row's JSON.
--   sent_autonomously     NULL for inbound rows (the concept doesn't apply).
--                         For outbound rows: whether personal_inbox_agent's
--                         reply_to_email fired without checking with the
--                         user first (the risk-based autonomy policy in
--                         tools/personal_inbox_tools.py) -- an audit trail
--                         of what Messa sent entirely on her own judgment,
--                         separate from the thread history itself. send_email
--                         (a fresh, non-reply send) always logs false here --
--                         it's a different kind of action, not an unprompted
--                         reply to an inbound stranger's email.
--   raw_json              Full raw payload (the inbound webhook's JSON body,
--                         or the outbound request+response) -- a superset of
--                         the columns above, kept so nothing is lost if a
--                         future feature needs a header this table doesn't
--                         break out explicitly.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'messa_email_direction') THEN
        CREATE TYPE messa_email_direction AS ENUM ('inbound', 'outbound');
    END IF;
END$$;

CREATE TABLE IF NOT EXISTS messa_email_messages (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    direction messa_email_direction NOT NULL,
    thread_id VARCHAR(998) NOT NULL,
    message_id VARCHAR(998) NOT NULL,
    in_reply_to VARCHAR(998),
    references_header TEXT,  -- "references" is a reserved word in some SQL contexts -- avoided here
    from_address VARCHAR(320) NOT NULL,
    to_address VARCHAR(320) NOT NULL,
    subject TEXT,
    body_text TEXT,
    raw_json TEXT,
    sent_autonomously BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_messa_email_messages_message_id UNIQUE (message_id)
);
CREATE INDEX IF NOT EXISTS ix_messa_email_messages_user_id ON messa_email_messages(user_id);
CREATE INDEX IF NOT EXISTS ix_messa_email_messages_thread_id ON messa_email_messages(thread_id);
CREATE INDEX IF NOT EXISTS ix_messa_email_messages_created_at ON messa_email_messages(created_at);
CREATE INDEX IF NOT EXISTS ix_messa_email_messages_from_address ON messa_email_messages(from_address);
CREATE INDEX IF NOT EXISTS ix_messa_email_messages_to_address ON messa_email_messages(to_address);
